### ISSUE TITLE
IntelliJ IDEA Ultimate 2016.2 Plugin Error

### ISSUE THREAD

**Issue by jandeel** [alirezamirian/Angular-Templates#4]
Using Angular Templates plugin version 1.1.2 and AngularJS plugin version 162.1120.12 with IntelliJ IDEA Ultimate version 2016.2 on Windows 7 and Solaris 10.

Getting the following error:

> Plugin Error
> Problems found loading plugins:
> Following plugins are incompatible with current IDE build: Angular Templates

Removing and re-adding the Angular Templates plugin does not fix the problem.

**Comment by alirezamirian** [comment]
Yes, I saw the compatibility issue and thanks to issue it.
I will try to provide a fixed version soon.

**Comment by krzysztof-kabala** [comment]
+1

the same for PhpStorm 2016.2 
`Problems found loading plugins: Following plugins are incompatible with current IDE build: Angular Templates`

**Comment by IJsLauw** [comment]
+1 

No fix in sight yet?

**Comment by alirezamirian** [comment]
I finally updated the plugin.
Please let me know if new version fixes the problem

**Comment by peckjon** [comment]
Updated this AM and conflict message has disappeared.  Thanks!
